# Generated by Django 4.1.1 on 2022-11-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdatamodel',
            old_name='data',
            new_name='date',
        ),
    ]
