# Generated by Django 4.1.7 on 2023-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0002_field_fieldcapacity_field_growingperioddays_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="PlantAvailableWater",
            field=models.FloatField(null=True),
        ),
    ]
