# Generated by Django 4.1.1 on 2022-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0002_rename_data_testdatamodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crops', models.CharField(max_length=20)),
                ('indicator', models.IntegerField()),
                ('lengthOfGrowingPeriodDays', models.IntegerField()),
                ('maxRootDepthInches', models.IntegerField()),
                ('maxAlllowableDeplitionPercentage', models.IntegerField()),
                ('columnForKc', models.IntegerField()),
                ('columnForDAP', models.IntegerField()),
                ('dAPforMaxRootDepth', models.IntegerField()),
            ],
        ),
    ]
