# Generated by Django 4.1.1 on 2023-01-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0003_cropinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('kcforCorn', models.CharField(max_length=30)),
                ('dAPforCorn', models.IntegerField()),
                ('kcforSoybean', models.CharField(max_length=30)),
                ('dAPforSoybean', models.IntegerField()),
                ('kcforCotton', models.CharField(max_length=30)),
                ('dAPforCotton', models.IntegerField()),
                ('kcforGrainSorghum', models.CharField(max_length=30)),
                ('dAPforGrainSorghum', models.IntegerField()),
                ('kcforGrainSugarcane', models.CharField(max_length=30)),
                ('dAPforGrainSugarcane', models.IntegerField()),
            ],
        ),
    ]
