# Generated by Django 4.1.1 on 2023-03-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0006_growthstage_soilcondition_soildrainagegroup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="userField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fieldId", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("size", models.FloatField()),
                ("plantDate", models.DateField()),
                (
                    "cropType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="droughtApp.cropinfo",
                    ),
                ),
            ],
        ),
    ]
