# Generated by Django 4.1.7 on 2023-07-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0006_alter_irrigation_fieldid_alter_results_fieldid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitconversion',
            old_name='flowMeterReadings',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='unitconversion',
            name='indicator',
        ),
    ]
