# Generated by Django 4.1.1 on 2023-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0007_userfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='hydrologicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
            ],
        ),
    ]
