# Generated by Django 4.1.7 on 2023-07-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0007_rename_flowmeterreadings_unitconversion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigation',
            name='UnitId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='droughtApp.unitconversion'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='FieldId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='droughtApp.field'),
        ),
    ]
