# Generated by Django 4.1.7 on 2023-07-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0008_irrigation_unitid_alter_irrigation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='UnitId',
            field=models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='droughtApp.unitconversion'),
        ),
    ]
