# Generated by Django 4.1.1 on 2023-03-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0009_soildrainagegroup1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soildrainagegroup',
            old_name='a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='soildrainagegroup',
            old_name='b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='soildrainagegroup',
            old_name='c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='soildrainagegroup',
            old_name='d',
            new_name='D',
        ),
    ]
