# Generated by Django 4.1.1 on 2023-03-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0010_rename_a_soildrainagegroup_a_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='soilDrainageGroup1',
        ),
    ]
