# Generated by Django 4.1.1 on 2023-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0011_delete_soildrainagegroup1'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropType',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('GrowingPeriodDays', models.IntegerField()),
                ('MaxRootDepth', models.IntegerField()),
                ('MaxAlllowableDeplition', models.IntegerField()),
                ('KC', models.IntegerField()),
                ('DAP', models.IntegerField()),
                ('MaxRootDepthDAP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='soilType',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='hydrologicgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='hydrologicgroup',
            name='indicator',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
