# Generated by Django 4.1.1 on 2023-03-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0012_croptype_soiltype_remove_hydrologicgroup_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrologicgroup',
            old_name='indicator',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='hydrologicgroup',
            old_name='name',
            new_name='Name',
        ),
    ]
