# Generated by Django 4.1.1 on 2023-03-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0014_alter_userfield_croptype_delete_cropinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('AuthenticationInfo', models.CharField(max_length=50)),
            ],
        ),
    ]
