# Generated by Django 4.1.1 on 2023-03-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0015_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Acreage', models.IntegerField()),
                ('PlantDate', models.DateField()),
                ('CropTypeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='droughtApp.croptype')),
                ('HydrologicGroupTypeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='droughtApp.hydrologicgroup')),
                ('OwnerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='droughtApp.user')),
                ('SoilTypeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='droughtApp.soiltype')),
            ],
        ),
    ]
