# Generated by Django 4.1.1 on 2023-03-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0016_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='irrigation',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('FieldId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='droughtApp.field')),
            ],
        ),
    ]
