# Generated by Django 4.1.1 on 2023-04-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0019_alter_field_croptypeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='indicator',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='initialConditions',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='ratio',
            new_name='Ratio',
        ),
        migrations.AlterField(
            model_name='field',
            name='SoilMoistureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.soilmoisture'),
        ),
    ]
