# Generated by Django 4.1.1 on 2023-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0023_alter_cropperiod1_croptypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltype',
            name='AveragePlantAvailableWater',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='PermanentWiltingPoint',
            field=models.FloatField(null=True),
        ),
    ]
