# Generated by Django 4.1.1 on 2023-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0025_delete_cropperiod_delete_soilcondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltype',
            name='FieldCapacity',
            field=models.FloatField(null=True),
        ),
    ]
