# Generated by Django 4.1.7 on 2023-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "droughtApp",
            "0027_rename_maxalllowabledeplition_croptype_maxalllowabledepletion_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="growthStage",
        ),
        migrations.RemoveField(
            model_name="field",
            name="CropPeriodId",
        ),
        migrations.AlterField(
            model_name="field",
            name="Latitude",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name="field",
            name="Longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="field",
            name="Name",
            field=models.CharField(max_length=150),
        ),
    ]
