# Generated by Django 4.1.7 on 2023-04-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0028_delete_growthstage_remove_field_cropperiodid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="cropPeriod1",
            new_name="cropPeriod",
        ),
    ]
