# Generated by Django 4.1.7 on 2023-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0033_rename_hydrologicgrouptypeid_field_hydrologicgroupid"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="Elevation",
            field=models.FloatField(null=True),
        ),
    ]
