# Generated by Django 4.1.7 on 2023-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "droughtApp",
            "0035_rename_maxalllowabledepletion_croptype_maxallowabledepletion",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="soiltype",
            name="Name",
            field=models.CharField(max_length=50),
        ),
    ]
