# Generated by Django 4.1.1 on 2023-01-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0004_cropperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropperiod',
            old_name='dAPforGrainSorghum',
            new_name='dAPforSorghum',
        ),
        migrations.RenameField(
            model_name='cropperiod',
            old_name='dAPforGrainSugarcane',
            new_name='dAPforSugarcane',
        ),
        migrations.RenameField(
            model_name='cropperiod',
            old_name='kcforGrainSugarcane',
            new_name='kcforSugarcane',
        ),
    ]
