# Generated by Django 4.1.1 on 2023-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0005_rename_dapforgrainsorghum_cropperiod_dapforsorghum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='growthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=20)),
                ('indicator', models.IntegerField()),
                ('emergence', models.CharField(max_length=30)),
                ('initialMoistureCheck', models.CharField(max_length=30)),
                ('irrigationInitiation', models.CharField(max_length=30)),
                ('irrigationTermination', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='soilCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilTexture', models.CharField(max_length=30)),
                ('indicator', models.IntegerField()),
                ('averagePlantAvailableWaterInFt', models.FloatField()),
                ('averagePlantAvailableWaterInIn', models.FloatField()),
                ('permanentWiltingPointInIn', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='soilDrainageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionForCN', models.CharField(max_length=30)),
                ('indicator', models.IntegerField()),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='soilMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialConditions', models.CharField(max_length=30)),
                ('indicator', models.IntegerField()),
                ('ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='unitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowMeterReadings', models.CharField(max_length=30)),
                ('indicator', models.IntegerField()),
                ('units', models.CharField(max_length=30)),
                ('conversion', models.FloatField()),
            ],
        ),
    ]
