# Generated by Django 4.1.1 on 2023-03-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0013_rename_indicator_hydrologicgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='cropType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='droughtApp.croptype'),
        ),
        migrations.DeleteModel(
            name='cropInfo',
        ),
    ]
