# Generated by Django 4.1.1 on 2023-04-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0017_irrigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropPeriod1',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('CropTypeId', models.IntegerField(null=True)),
                ('KC', models.CharField(max_length=30)),
                ('DAP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cropType1',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('GrowingPeriodDays', models.IntegerField()),
                ('MaxRootDepth', models.IntegerField()),
                ('MaxAlllowableDeplition', models.IntegerField()),
                ('MaxRootDepthDAP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='drainageType',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('ValueField', models.IntegerField()),
                ('HydrologicGroupTypeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='droughtApp.hydrologicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='soilMoisture1',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Ratio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='soilmoisture',
            name='id',
        ),
        migrations.AddField(
            model_name='soiltype',
            name='AveragePlantAvailableWater',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='PermanentWiltingPoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='CropTypeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisture',
            name='indicator',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='userField',
        ),
        migrations.AddField(
            model_name='field',
            name='CropPeriodId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.cropperiod1'),
        ),
        migrations.AddField(
            model_name='field',
            name='DrainageTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.drainagetype'),
        ),
        migrations.AddField(
            model_name='field',
            name='SoilMoistureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.soilmoisture1'),
        ),
    ]
