# Generated by Django 4.1.1 on 2023-04-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0018_cropperiod1_croptype1_drainagetype_soilmoisture1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='CropTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.croptype1'),
        ),
    ]
