# Generated by Django 4.1.1 on 2023-04-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0020_rename_indicator_soilmoisture_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='Id',
            new_name='indicator',
        ),
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='Name',
            new_name='initialConditions',
        ),
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='Ratio',
            new_name='ratio',
        ),
        migrations.AlterField(
            model_name='field',
            name='SoilMoistureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.soilmoisture1'),
        ),
    ]
