# Generated by Django 4.1.1 on 2023-04-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0022_alter_drainagetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropperiod1',
            name='CropTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.croptype1'),
        ),
    ]
