# Generated by Django 4.1.1 on 2023-04-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0024_alter_soiltype_averageplantavailablewater_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cropPeriod',
        ),
        migrations.DeleteModel(
            name='soilCondition',
        ),
        migrations.DeleteModel(
            name='soilDrainageGroup',
        ),
        migrations.DeleteModel(
            name='soilMoisture',
        ),
        migrations.DeleteModel(
            name='testdatamodel',
        ),
        migrations.RenameField(
            model_name='cropperiod1',
            old_name='KC',
            new_name='CropCoefficient',
        ),
        migrations.RenameField(
            model_name='cropperiod1',
            old_name='DAP',
            new_name='DaysAfterPlanting',
        ),
        migrations.RemoveField(
            model_name='croptype',
            name='DAP',
        ),
        migrations.RemoveField(
            model_name='croptype',
            name='KC',
        ),
        migrations.AlterField(
            model_name='cropperiod1',
            name='CropTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.croptype'),
        ),
        migrations.AlterField(
            model_name='field',
            name='CropTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='droughtApp.croptype'),
        ),
        migrations.DeleteModel(
            name='cropType1',
        ),
    ]
