# Generated by Django 4.1.7 on 2023-04-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0026_soiltype_fieldcapacity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="croptype",
            old_name="MaxAlllowableDeplition",
            new_name="MaxAlllowableDepletion",
        ),
        migrations.RenameField(
            model_name="croptype",
            old_name="MaxRootDepthDAP",
            new_name="MaxRootDepthDaysAfterPlanting",
        ),
    ]
