# Generated by Django 4.1.7 on 2023-04-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0030_rename_soilmoisture1_soilmoisture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soilmoisture",
            old_name="Ratio",
            new_name="InitialSoilMoisturePercent",
        ),
    ]
