# Generated by Django 4.1.7 on 2023-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0031_rename_ratio_soilmoisture_initialsoilmoisturepercent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drainagetype",
            old_name="ValueField",
            new_name="DrainageValue",
        ),
        migrations.RenameField(
            model_name="drainagetype",
            old_name="HydrologicGroupTypeId",
            new_name="HydrologicGroupId",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="AuthenticationInfo",
            new_name="AuthenticationId",
        ),
        migrations.AlterField(
            model_name="hydrologicgroup",
            name="Name",
            field=models.CharField(max_length=1),
        ),
    ]
