# Generated by Django 4.1.7 on 2023-04-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("droughtApp", "0032_rename_valuefield_drainagetype_drainagevalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="HydrologicGroupTypeId",
            new_name="HydrologicGroupId",
        ),
    ]
