<<<<<<< HEAD
# Generated by Django 4.1.1 on 2023-04-10 18:18
=======
# Generated by Django 4.1.7 on 2023-04-10 17:46
>>>>>>> e360e72e0afb2449a9e047b1580e71fe40763ecc

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('droughtApp', '0034_field_elevation'),
=======
        ("droughtApp", "0034_field_elevation"),
>>>>>>> e360e72e0afb2449a9e047b1580e71fe40763ecc
    ]

    operations = [
        migrations.RenameField(
<<<<<<< HEAD
            model_name='croptype',
            old_name='MaxAlllowableDepletion',
            new_name='MaxAllowableDepletion',
=======
            model_name="croptype",
            old_name="MaxAlllowableDepletion",
            new_name="MaxAllowableDepletion",
>>>>>>> e360e72e0afb2449a9e047b1580e71fe40763ecc
        ),
    ]
