# Generated by Django 4.1.1 on 2023-05-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droughtApp', '0035_rename_maxalllowabledepletion_croptype_maxallowabledepletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='FieldCapacity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='GrowingPeriodDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='PermanentWiltingPoint',
            field=models.FloatField(null=True),
        ),
    ]
